name: valhalla-tracker
base: core18
version: '0.1.8'
summary: A live midi sequencer for JACK
description: |
  Valhalla Tracker is a MIDI sequencing companion for your GNU/Linux audio setup

grade: devel
confinement: devmode

architectures:
  - build-on: amd64

apps:
  valhalla-tracker:
    command: desktop-launch vht
    extensions: [gnome-3-28]
    plugs:
    - home

parts:
  libvht:
    source: .
    plugin: python
    stage-packages:
    - libjack-dev
    - gir1.2-gtk-3.0
    - gir1.2-vte-2.91
    - python3-gi
    - python3-gi-cairo

