name: valhalla-tracker
base: core20
version: git
summary: A live midi sequencer for JACK
description: |
  Valhalla Tracker is a MIDI sequencing companion for your GNU/Linux audio setup

grade: stable
confinement: strict
license: GPL-3.0

architectures:
  - build-on: amd64

apps:
  valhalla-tracker:
    command: desktop-launch vht
    extensions: [gnome-3-34]
    plugs:
    - home
    - network
    - jack2

parts:
  libvht:
    source: .
    plugin: python
    stage-packages:
    - libjack-jackd2-dev
    - gir1.2-gtk-3.0
    - gir1.2-vte-2.91
    - python3-gi
    - python3-gi-cairo

