name: valhalla-tracker
base: core18
version: '0.1.8'
summary: A live midi sequencer for JACK
description: |
  Valhalla Tracker is a MIDI sequencing companion for your GNU/Linux audio setup

grade: devel
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  valhalla-tracker:
    command: vht

parts:
  libvht:
    source: .
    plugin: python
    stage-packages:
    - libjack-jackd2-dev
    - python3-gi
    - python3-gi-cairo


